// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skfhovlzrhcaxfspnrln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrZmhvdmx6cmhjYXhmc3BucmxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMzU0MzgsImV4cCI6MjA2MTYxMTQzOH0.gEGuAz5NjMECO9MNGuDgKqo5DoYEVWXICtLxMIGJabo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);